
package vista;

import java.sql.*;
import java.awt.Color;
import java.awt.Font;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import clases.Conexion;
import com.mysql.cj.protocol.Resultset;
import java.awt.AWTEventMulticaster;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;



public class GestiondeUsuarios extends javax.swing.JFrame {

         public static String user_update;     
        DefaultTableModel model = new DefaultTableModel ();
        
       
  
    
String encabezado = "nombre";


 
    public GestiondeUsuarios() {
        initComponents();
        
        setLayout(null);
        
        getContentPane().setBackground(new Color(48,48,48));
        setSize(600,420);
        setLocation(105,75);
        setResizable(false);
         setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE );
        
       

     
        
          label_alluser= new JLabel("TODOS LOS USUARIOS");
              label_alluser.setBounds(210, 40, 300, 30);
               label_alluser.setFont(new Font("SF Pro Rounded Heavy", 1, 18));
                label_alluser.setForeground(new Color(255,255,255));
                add( label_alluser);
       
                
                JTable tabla_usuario = new JTable(model);
                JScrollPane scrolltablauser = new  JScrollPane(tabla_usuario);
                scrolltablauser.setBounds(0,105,600,300);
                add(scrolltablauser);
           
                model.addColumn("ID");
                 model.addColumn("Nombre");
                 model.addColumn("Usuario");
                 model.addColumn("Estado");
                  model.addColumn("Permisos");
                  model.addColumn("Agregador por");
                 
                  
                  try {
            
                      Connection connsiet = (Connection) Conexion.conectar();
                      PreparedStatement pst = connsiet.prepareStatement(
                              "select id_usuario, nombre_usuario, username, status_usuario, tipo_usuario, registrado_por from usuarios");
                      
                      ResultSet rsttab = pst.executeQuery();
                      
                      while(rsttab.next()){
                      
                          Object[] fila = new Object [6];
                          
                          
                          for(int i = 0; i < 6; i++){
                          
                              fila[i] = rsttab.getObject(i+ 1);
                          
                          }
                       model.addRow(fila);
                      
                      }
                       connsiet.close();
                    
        } catch (SQLException g) {
                      System.err.println("error al conectar con la basede dato y llenado de tabala " + g);
                      JOptionPane.showConfirmDialog(null, "ERROR, por favor contacte con el administrador");
        }
                  
                  
                  
                      
                  tabla_usuario.addMouseListener(new MouseAdapter(){
                                  @Override
                                  
                                  public void mouseClicked(MouseEvent e){
                                  
                                  int fila_point = tabla_usuario.rowAtPoint(e.getPoint());
                                  int columna = 2;
                                  
                                  if(fila_point >  -1){
                                    
                                      user_update = (String)model.getValueAt(fila_point, columna);
                                    
                                      
                                  }
                                      
                                      
                                  }
             
});


       
       

                 
    }

    /*mis elementos*/
    JLabel label_alluser;

    JScrollPane scrolluser;
   
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestiondeUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestiondeUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestiondeUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestiondeUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestiondeUsuarios().setVisible(true);
            }
        });
    }

    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
