
package vista;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.*;
import javax.swing.border.Border;
import java.sql.*;
import clases.Conexion;
import java.awt.Toolkit;


/**
 *
 * @author perse
 */
public class Login extends javax.swing.JFrame implements ActionListener {
    
    public static String user = "";
    String pass = "";
public static  String tipo_usuario = "";
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLayout(null);
        setSize(400, 500);
        setLocationRelativeTo(null);
        setResizable(false);
        getContentPane().setBackground(new Color(75, 75, 75));
        
        
        
        
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaper_login.png");
        label_wallpaper = new JLabel();
        label_wallpaper.setBounds(5, 50, 300
                , 300);
        label_wallpaper.setIcon(new ImageIcon(wallpaper.getImage().getScaledInstance(400, 400, Image.SCALE_SMOOTH)));
        add(label_wallpaper);
        
       
        
       
        
        JButton boton_acceder = new  JButton("Acceder");
        boton_acceder.setBounds(140, 370, 135, 30);
         boton_acceder.setBackground(new Color(235,235,235));
         boton_acceder.setFont(new Font("SF Pro Rounded Semibold", 1, 24));
         boton_acceder.setForeground((new Color(100,100,100)));
        Border border_botonacceder = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY);
        boton_acceder.setBorder(border_botonacceder);
 add(boton_acceder);
        
        add(boton_acceder);
        boton_acceder.addActionListener(this);
        
        
         txt_user.setBounds(115, 250, 200, 20);
         txt_user.setFont(new Font("SF Pro Rounded Semibold", 0, 16));
         txt_user.setForeground(new Color(255,255,255));
         txt_user.setBackground(new Color(74,74,74));
         Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY);
         txt_user.setHorizontalAlignment(JTextField.CENTER);
        
         txt_user.setBorder(border);
 
 add(txt_user);
 
 
 
         Border border_txtpassword = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY);
         txt_password.setBounds(115, 300, 200, 20);
         txt_password.setBackground(new Color(74,74,74));
         txt_password.setFont(new Font("SF Pro Rounded Semibold", 0, 16));
         txt_password.setForeground(new Color(255,255,255));
         txt_password.setHorizontalAlignment(JTextField.CENTER);
         
        
         
 txt_user.setBorder(border_txtpassword);
 add(txt_password);
 
 label_txtusername = new JLabel("Usuario :");
 label_txtusername.setFont(new Font("SF Pro Rounded", 1, 18));
 label_txtusername.setForeground(new Color(255,255,255));
 label_txtusername.setBounds(175, 275, 100, 20);
 add(label_txtusername);
 
  label_txtpassword = new JLabel("Contraseña :");
  label_txtpassword.setForeground(new Color(255,255,255));
  label_txtpassword.setFont(new Font("SF Pro Rounded Semibold", 1, 18));
 label_txtpassword.setBounds(165, 325, 150, 20);
 add(label_txtpassword);
 
 
    }
 JTextField txt_user = new JTextField();
 JPasswordField txt_password = new JPasswordField();  
    
 @Override
        public Image getIconImage() {
        
            Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/loib.png"));
            return retValue;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
   
     
      
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
        });
    }
    
    
    
   
    JLabel label_wallpaper, label_txtusername, label_txtpassword;
    
    
    
    @Override
    public void actionPerformed(ActionEvent e) {

        user = txt_user.getText().trim();
        pass = txt_password.getText().trim();
            
         if(!user.equals("") || !pass.equals("")){
             
             try{
                 
                Connection bd = Conexion.conectar();
                PreparedStatement pst;
                 pst = bd.prepareStatement(
                         "select tipo_usuario, status_usuario from usuarios where username = '" + user
                                 + "' and password_usuario = '" + pass + "'");
                 
                ResultSet rs = pst.executeQuery();
                
                if(rs.next()){
                    
                 tipo_usuario = rs.getString("tipo_usuario");
                    String status_usuario = rs.getString("status_usuario");
                    
                
                    if(tipo_usuario.equalsIgnoreCase("Administrador") && status_usuario.equalsIgnoreCase("Activo")){
                        
                        dispose();
                        new Administrador().setVisible(true);
                    
                    } else if(tipo_usuario.equalsIgnoreCase("Estandar") && status_usuario.equalsIgnoreCase("Activo")){
                    
                        dispose();
                        new Estandar().setVisible(true);
                    
                    } 
                    
                        
                        
                    } else {
                    JOptionPane.showMessageDialog(null, "El nombre de usuario o contraseña son incorrectos");
                
                }
                    
                
                
             
             } catch (SQLException g) {
                 
                 System.err.println("!atencion desarrollador, !error en el boton acceder" + e);
                 JOptionPane.showMessageDialog(
                         null, "error alm inicar sesion, contacte al administrador!!");
                         
             
             
                 
             }
            
            
            
        
        
        } else {
            
         JOptionPane.showMessageDialog(null, "debes llenar todo los campos");
         
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
